### ISSUE TITLE
Autenticação

### ISSUE THREAD

**Issue by leorobles** [silici0/webmotorsApi#1]
Olá, tudo bem? Primeiramente parabéns pelo projeto, excelente iniciativa.
Estou adaptando para Carros seu projeto. Porém fui autenticar e recebi erro, eu dei um print na hash e esse foi o erro "Erro na Autenticacao",
fiz um print_r também do $result = $webmotorsLoginServiceAutenticar->getResult()

WebmotorsLoginStructAutenticarResponse Object ( [autenticarResult] => WebmotorsLoginStructAutenticacaoSistemaRevendedorWM Object ( [HashAutenticacao] => Erro na Autenticacao [CodigoRetorno] => 400 [result:WebmotorsLoginWsdlClass:private] => [lastError:WebmotorsLoginWsdlClass:private] => [internArrayToIterate:WebmotorsLoginWsdlClass:private] => [internArrayToIterateIsArray:WebmotorsLoginWsdlClass:private] => [internArrayToIterateOffset:WebmotorsLoginWsdlClass:private] => ) [result:WebmotorsLoginWsdlClass:private] => [lastError:WebmotorsLoginWsdlClass:private] => [internArrayToIterate:WebmotorsLoginWsdlClass:private] => [internArrayToIterateIsArray:WebmotorsLoginWsdlClass:private] => [internArrayToIterateOffset:WebmotorsLoginWsdlClass:private] => ) Erro na Autenticacao

Mudou algo na autenticação da WM?
Abraço

**Comment by silici0** [comment]
Essas conexões são para Motos, acredito que para Carros seja diferente as url e autenticação, se quiser me manda as url e gero para você os arquivos.
So para ter certeza, essa autenticação usa : 'https://integracao.webmotors.com.br/wsLoginSistemaRevendedor.asmx?wsdl'

**Comment by leorobles** [comment]
@silici0  Testei essa não foi. Então não sei se a autenticação é diferente a api está nesse link né https://www.webmotors.com.br/integracaoRevendedor/wsEstoqueRevendedorWebMotors.asmx?op=ObterEstoqueAtual
Será essa a autenticação? https://www.webmotors.com.br/integracaoRevendedor/wsLoginSistemaRevendedor.asmx?op=autenticar
Se quiser me add em outro local posso te mandar os arquivos que mudei tb, as função são bem parecidas exceto pelo fato de ter Motos Na frente das funções.

**Comment by silici0** [comment]
@leorobles A autenticação aparentemente é o mesmo método do que eu uso, tente utilizar o SoapUI para testar os seus dados de autenticacao (cnpj, email e senha), se tiver um canal de suporte confirme com a webmotors, se quiser meu skype é o mesmo nick.

**Comment by silici0** [comment]
Estou fechando pois testei e o login funciona tanto para Motos/Carros, porem no carros muda a url da API para trazer os dados e login/senha, essa api funciona.
